# CI 项目
name: workflow

# CI 权限
permissions: write-all

# CI 计划
on:
  # 自动运行: 每天早上 4 点
  schedule:
    - cron: 0 20 * * *
  # 手动运行
  workflow_dispatch:
    inputs:
      TEST:
        description: 'Test'
        required: false
        type: string
        default: 'value'

# CI 环境
env:
  # GITHUB ENV
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # CI ENV
  CI_TEST: ${{inputs.TEST}}

# CI 任务
jobs:
  template:
    name: workflow
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutProject
        uses: actions/checkout@main

      - name: InitWorkflow
        run: |
          WorkflowPath="$RUNNER_TEMP/Workflow-$(uuidgen | tr -d '-')"
          git clone --depth=1 https://github.com/zero-dream/workflow.git "$WorkflowPath/"
          chmod +x "$WorkflowPath/zerodream/main/init.sh"
          source "$WorkflowPath/zerodream/main/init.sh"
          # --------------------------------------------------
          source "$ZD_ScriptLibPath/hook.sh"
          hook 'Workflow/InitWorkflow'

      - name: WriteCode
        run: |
          # ... code
